name: Lint Code Base

on:
  push:
  pull_request:
    branches: [master]

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} #Checkout Code
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        fetch-depth: 0
