name: Lint Code Base

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    name: what does this do
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  linter:
      name: Lint Code Base
      runs-on: ubuntu-latest

      steps:
      - name: Lint Code Base
      - uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}