name: Lint Code Base

on:
  push:
#    branches-ignore: [master]
  pull_request:
  branches: [master]

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js ${{ matrix.node-version }} #Checkout Code
    - uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}
        fetch-depth: 0
